config/routes.rb
Rails.application.routes.draw do
  resources :ideas

   resources :ideas do
  member do
    put "like", to: "ideas#upvote"
    put "dislike", to: "ideas#downvote"
  end
end

  resources :apps

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  

  resources :questions do 
    resources :comments
  end

  resources :accelerators

  resources :stresses

  resources :investors

  resources :fundings

  resources :pitches

  resources :marketplaces

  resources :jobs

  resources :events

  resources :founders

  resources :spaces

  resources :posts

  get "search" => "search#index"

  get '8a8618faa3115ed1.html' => 'home#8a8618faa3115ed1.html'

  root 'home#index'

end

app/models/accelerator.rb
class Accelerator < ActiveRecord::Base
	validates_presence_of  :title, :body, :contact_info, :location

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/app.rb
class App < ActiveRecord::Base
  validates_presence_of  :title, :body, :tagline, :link
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :question
	belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base

	validates_presence_of :location, :title, :body, :on => :create, :message => "can't be blank"
end

app/models/founder.rb
class Founder < ActiveRecord::Base

validates_presence_of :compensation, :title, :body, :contact_info

validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
end

app/models/funding.rb
class Funding < ActiveRecord::Base
	validates_presence_of :link, :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	acts_as_votable
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end

end

app/models/investor.rb
class Investor < ActiveRecord::Base
	validates_presence_of :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/job.rb
class Job < ActiveRecord::Base
	validates_presence_of  :title, :body, :contact_info, :location, :compensation

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/marketplace.rb
class Marketplace < ActiveRecord::Base
	validates_presence_of :title, :body, :contact_info, :location

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
	validates_presence_of :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/space.rb
class Space < ActiveRecord::Base
	validates_presence_of :location, :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/stress.rb
class Stress < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments
	has_many :questions
  acts_as_voter

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:twitter]

  has_attached_file :avatar, :styles => { :small => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20],
          image: auth.info.image.sub("_mini", "")
        )

        # check if confirmable is enabled
        user.skip_confirmation! if user.respond_to?(:skip_confirmation)
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end

    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    def index
    @post = Post.last
    q = params[:q]
    @founders = Founder.search(title_cont: q).result
    @jobs = Job.search(title_cont: q).result
    @stresses = Stress.search(title_cont: q).result
    @accelerators = Accelerator.search(title_cont: q).result
    @events = Event.search(title_cont: q).result
    @fundings = Funding.search(title_cont: q).result
    @marketplaces = Marketplace.search(title_cont: q).result
    @pitches = Pitch.search(title_cont: q).result
    @spaces = Space.search(title_cont: q).result
    end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<div class="container">

<% @results = @accelerators + @jobs + @events + @founders + @fundings + @marketplaces + @pitches + @spaces + @stresses %>

<% unless @accelerators.blank? %>
<div class="row">
<div class="post-title">Accelerators</div>
<% @accelerators.each do |accelerator| %>
<%= link_to accelerator.title, accelerator_path(accelerator)  %></br>
<% end %>
</div>
</br>
<% end %>

<% unless @events.blank? %>
<div class="row">
<div class="post-title">Events</div>
<% @events.each do |event| %>
<%= link_to event.title, event_path(event)  %></br>
<% end %>
</div>
</br>
<% end %>

<% unless @founders.blank? %>
<div class="row">
<div class="post-title">Founders</div>
<% @founders.each do |founder| %>
<%= link_to founder.title, founder_path(founder)  %></br>
<% end %>
</div>
</br>
<% end %>

<% unless @jobs.blank? %>
<div class="row">
<div class="post-title">Jobs</div>
<% @jobs.each do |job| %>
<%= link_to job.title, job_path(job)  %></br>
<% end %>
</div>
</br>
<% end %>

<% unless @marketplaces.blank? %>
<div class="row">
<div class="post-title">Marketplaces</div>
<% @marketplaces.each do |marketplace| %>
<%= link_to marketplace.title, marketplace_path(marketplace)  %></br>
<% end %>
</div>
</br>
<% end %>

<% unless @pitches.blank? %>
<div class="row">
<div class="post-title">Pitches</div>
<% @pitches.each do |pitch| %>
<%= link_to pitch.title, pitch_path(pitch)  %></br>
<% end %>
</div>
</br>
<% end %>

<% unless @spaces.blank? %>
<div class="row">
<div class="post-title">Spaces</div>
<% @spaces.each do |space| %>
<%= link_to space.title, space_path(space)  %></br>
<% end %>
</div>
</br>
<% end %>

<% unless @stresses.blank? %>
<div class="row">
<div class="post-title">HAAAAAAAAA</div>
<% @stresses.each do |stress| %>
<%= link_to stress.title, stress_path(stress)  %></br>
<% end %>
</div>
</br>
<% end %>


</div>

<%= link_to 'Back', root_path %>