config/routes.rb
Rails.application.routes.draw do
  resources :ideas

   resources :ideas do
  member do
    put "like", to: "ideas#upvote"
    put "dislike", to: "ideas#downvote"
  end
end

  resources :apps

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  

  resources :questions do 
    resources :comments
  end

  resources :accelerators

  resources :stresses

  resources :investors

  resources :fundings

  resources :pitches

  resources :marketplaces

  resources :jobs

  resources :events

  resources :founders

  resources :spaces

  resources :posts

  get "search" => "search#index"

  get '8a8618faa3115ed1.html' => 'home#8a8618faa3115ed1.html'

  root 'home#index'

end

app/models/marketplace.rb
class Marketplace < ActiveRecord::Base
	validates_presence_of :title, :body, :contact_info, :location

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/controllers/marketplaces_controller.rb
class MarketplacesController < ApplicationController
  before_action :set_marketplace, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "grigerny", password: "6764", except: [:index, :show, :new, :create] 

  # GET /marketplaces
  # GET /marketplaces.json
  def index
    @post = Post.last
    @marketplaces = Marketplace.all
  end

  # GET /marketplaces/1
  # GET /marketplaces/1.json
  def show
    @post = Post.last
  end

  # GET /marketplaces/new
  def new
    @post = Post.last
    @marketplace = Marketplace.new
  end

  # GET /marketplaces/1/edit
  def edit
    @post = Post.last
  end

  # POST /marketplaces
  # POST /marketplaces.json
  def create
    @post = Post.last
    @marketplace = Marketplace.create(marketplace_params)

    respond_to do |format|
      if @marketplace.save
        format.html { redirect_to @marketplace, notice: 'Marketplace was successfully created.' }
        format.json { render :show, status: :created, location: @marketplace }
      else
        format.html { render :new }
        format.json { render json: @marketplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marketplaces/1
  # PATCH/PUT /marketplaces/1.json
  def update
    respond_to do |format|
      if @marketplace.update(marketplace_params)
        format.html { redirect_to @marketplace, notice: 'Marketplace was successfully updated.' }
        format.json { render :show, status: :ok, location: @marketplace }
      else
        format.html { render :edit }
        format.json { render json: @marketplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marketplaces/1
  # DELETE /marketplaces/1.json
  def destroy
    @marketplace.destroy
    respond_to do |format|
      format.html { redirect_to marketplaces_url, notice: 'Marketplace was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marketplace
      @marketplace = Marketplace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marketplace_params
      params[:marketplace].permit(:location, :title, :body, :image, :contact_info)
    end
end

app/helpers/marketplaces_helper.rb
module MarketplacesHelper
end

app/views/marketplaces/_form.html.erb
<%= form_for(@marketplace) do |f| %>
  <% if @marketplace.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marketplace.errors.count, "error") %> prohibited this marketplace from being saved:</h2>

      <ul>
      <% @marketplace.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row-fluid">
  Location:
  <div class="field">
  <%=   f.text_field :location %></br>
  </div>
  Title:
  <div class="field">
  <%=   f.text_field :title %></br>
  </div>
  Body:
  <div class="field">
   <%= f.text_area :body, :class => "tinymce", :rows => 20, :cols => 120, :placeholder => "What are you selling?" %></br>
  </div>
  Email: 
  <div class="field">
  <%= f.text_field :contact_info %></br></br>
  </div>


  <div class="actions">
    <%= f.submit "Add to Marketplace" %>
  </div>
  </div>
<% end %>
<%= tinymce %>

app/views/marketplaces/edit.html.erb
<h1>Editing Marketplace</h1>

<%= render 'form' %>

<%= link_to 'Show', @marketplace %> |
<%= link_to 'Back', marketplaces_path %>

app/views/marketplaces/index.html.erb
<p id="notice"><%= notice %></p>

<center><div class="category-title"> <%= link_to 'Post to Marketplace', new_marketplace_path %></div></center></br>

  <tbody>
    <% @marketplaces.reverse.each do |marketplace| %>
      <tr>
       <td>
         <% if (marketplace.created_at) > (24.hours.ago) == true %>
         <div class="time-new"><%= "Today" %> </div>
         <% else %>
         <div class="time">Last updated <%= time_ago_in_words(marketplace.created_at) %> ago </div>
         <% end %>
       </td>
        <td><%= link_to marketplace_path(marketplace) do %> 
        <div class="post-title"><%= marketplace.title %> - <%= marketplace.location %></div></br>
        <% end %> </td>
      </tr>
    <% end %>
  </tbody>
  <%= link_to 'Back', root_url %>

app/views/marketplaces/new.html.erb
<h1>Post to Marketplace</h1>

<%= render 'form' %>

<%= link_to 'Back', marketplaces_path %>

app/views/marketplaces/show.html.erb
<p id="notice"><%= notice %></p>
<div class="title">Marketplace</div></br>

<div class="category-title"><%= @marketplace.title %></div></br>
Location: <%= @marketplace.location %></br>
<%= auto_link(simple_format(@marketplace.body)) %></br></br>
Contact: <%= mail_to @marketplace.contact_info %></br>


<%= link_to 'Back', marketplaces_path %>