config/routes.rb
Rails.application.routes.draw do
  resources :ideas

   resources :ideas do
  member do
    put "like", to: "ideas#upvote"
    put "dislike", to: "ideas#downvote"
  end
end

  resources :apps

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  

  resources :questions do 
    resources :comments
  end

  resources :accelerators

  resources :stresses

  resources :investors

  resources :fundings

  resources :pitches

  resources :marketplaces

  resources :jobs

  resources :events

  resources :founders

  resources :spaces

  resources :posts

  get "search" => "search#index"

  get '8a8618faa3115ed1.html' => 'home#8a8618faa3115ed1.html'

  root 'home#index'

end

app/models/accelerator.rb
class Accelerator < ActiveRecord::Base
	validates_presence_of  :title, :body, :contact_info, :location

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/app.rb
class App < ActiveRecord::Base
  validates_presence_of  :title, :body, :tagline, :link
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :question
	belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base

	validates_presence_of :location, :title, :body, :on => :create, :message => "can't be blank"
end

app/models/founder.rb
class Founder < ActiveRecord::Base

validates_presence_of :compensation, :title, :body, :contact_info

validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
end

app/models/funding.rb
class Funding < ActiveRecord::Base
	validates_presence_of :link, :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	acts_as_votable
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end

end

app/models/investor.rb
class Investor < ActiveRecord::Base
	validates_presence_of :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/job.rb
class Job < ActiveRecord::Base
	validates_presence_of  :title, :body, :contact_info, :location, :compensation

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/marketplace.rb
class Marketplace < ActiveRecord::Base
	validates_presence_of :title, :body, :contact_info, :location

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
	validates_presence_of :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/space.rb
class Space < ActiveRecord::Base
	validates_presence_of :location, :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/stress.rb
class Stress < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments
	has_many :questions
  acts_as_voter

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:twitter]

  has_attached_file :avatar, :styles => { :small => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20],
          image: auth.info.image.sub("_mini", "")
        )

        # check if confirmable is enabled
        user.skip_confirmation! if user.respond_to?(:skip_confirmation)
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end

    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	@users = User.all
	  @post = Post.last
    q = params[:q]
    @founders = Founder.search(title_cont: q).result
    @jobs = Job.search(title_cont: q).result
    end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/home/index.html.erb
<!-- HeedUser feedback widget code starts here -->
<script>
(function () { var hu = document.createElement("script"); hu.type = "text/javascript"; hu.async = true; hu.src = "//www.heeduser.com/supfiles/Script/widget.js"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hu, s); })()
</script>





<% client = Twitter::REST::Client.new do |config|
  config.consumer_key        = "pqP3no6J5RXNfkt9aya4ZvDUi"
  config.consumer_secret     = "UPbObOKSszw8ODABV4Kbmf2NyIFqG2s9Pt290FmTgY0eaKsLc8"
  config.access_token        = "37588554-8FfLTW83PfTGaQqFWsd2BPZhTlTMPbw1m6bS0U6XD"
  config.access_token_secret = "oLAUuXg4UqTPvbWWMHyBpHalpXdREKf64OBDIXr20Eh7h"
end %>


<div class="title-community">Community</div>
<div class="container">
<div class="row">

<% @users.each do |user| %>	
	<% if user.image.present? %>
	<%= link_to "#{"http://www.twitter.com/" + user.username}" do %> 
	<%= image_tag(user.image, :class => "no-pic-css")%>
	<% end %>
	<% else %>
	<%= image_tag('icon-user-default.png', :class => "no-pic-css") %>
	<% end %>
<% end %>
</div>
</div>
<hr>

<div class="row">

<div class="col-md-4">
<%= link_to accelerators_path, :class =>"post-title" do %>
Accelerate & Incubate
<% end %></br>
Find opportunities for your startup.
</div>

<div class="col-md-4">
<%= link_to apps_path, :class =>"post-title" do %>
Apps & Products
<% end %></br>
New apps everyday
</div>

<div class="col-md-4">
<%= link_to questions_path, :class =>"post-title" do %>
Ask & Answer
<% end %></br>
Reach our community of entrepreneurs.
</div>

</div>
</br></br>

<div class="row">

<div class="col-md-4">
<%= link_to events_path, :class =>"post-title" do %>
Events
<% end %></br>
Post and find relevant events near you.
</div>

<div class="col-md-4">
<%= link_to founders_path, :class =>"post-title" do %>
Founder Dating
<% end %></br>
Find a co-founder and start something.
</div>

<div class="col-md-4">
<%= link_to fundings_path, :class =>"post-title" do %>
Fund Raising
<% end %></br>
Looking for funding? Share your story.
</div>

</div>

</br></br>

<div class="row">
	
<div class="col-md-4">
<%= link_to stresses_path, :class =>"post-title" do %>
Introductions
<% end %></br>
Introduce Yourself.
</div>
	
<div class="col-md-4">
<%= link_to investors_path, :class =>"post-title" do %>
Investors
<% end %></br>
Want to help fund a startup? Post here.
</div>


<div class="col-md-4">
<%= link_to jobs_path, :class =>"post-title" do %>
Jobs
<% end %></br>
Find & share work opportunities.
</div>

</div>
</br></br>

<div class="row">

<div class="col-md-4">
<%= link_to marketplaces_path, :class =>"post-title" do %>
Marketplace
<% end %></br>
Buy, Sell or Trade.
</div>

<div class="col-md-4">
<%= link_to spaces_path, :class =>"post-title" do %>
Office Space
<% end %></br>
Find & share co-working spaces here!
</div>


<div class="col-md-4">
<%= link_to pitches_path, :class =>"post-title" do %>
Startups
<% end %></br>
Share your startup with the community.
</div>

</div>