config/routes.rb
Rails.application.routes.draw do
  resources :ideas

   resources :ideas do
  member do
    put "like", to: "ideas#upvote"
    put "dislike", to: "ideas#downvote"
  end
end

  resources :apps

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  

  resources :questions do 
    resources :comments
  end

  resources :accelerators

  resources :stresses

  resources :investors

  resources :fundings

  resources :pitches

  resources :marketplaces

  resources :jobs

  resources :events

  resources :founders

  resources :spaces

  resources :posts

  get "search" => "search#index"

  get '8a8618faa3115ed1.html' => 'home#8a8618faa3115ed1.html'

  root 'home#index'

end

app/models/accelerator.rb
class Accelerator < ActiveRecord::Base
	validates_presence_of  :title, :body, :contact_info, :location

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/app.rb
class App < ActiveRecord::Base
  validates_presence_of  :title, :body, :tagline, :link
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :question
	belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base

	validates_presence_of :location, :title, :body, :on => :create, :message => "can't be blank"
end

app/models/founder.rb
class Founder < ActiveRecord::Base

validates_presence_of :compensation, :title, :body, :contact_info

validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
end

app/models/funding.rb
class Funding < ActiveRecord::Base
	validates_presence_of :link, :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	acts_as_votable
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end

end

app/models/investor.rb
class Investor < ActiveRecord::Base
	validates_presence_of :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/job.rb
class Job < ActiveRecord::Base
	validates_presence_of  :title, :body, :contact_info, :location, :compensation

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/marketplace.rb
class Marketplace < ActiveRecord::Base
	validates_presence_of :title, :body, :contact_info, :location

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
	validates_presence_of :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/space.rb
class Space < ActiveRecord::Base
	validates_presence_of :location, :title, :body, :contact_info

	validates_format_of :contact_info,:multiline => true, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

end

app/models/stress.rb
class Stress < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments
	has_many :questions
  acts_as_voter

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:twitter]

  has_attached_file :avatar, :styles => { :small => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20],
          image: auth.info.image.sub("_mini", "")
        )

        # check if confirmable is enabled
        user.skip_confirmation! if user.respond_to?(:skip_confirmation)
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end

    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row-fluid">
  Title:
  <div class="field">
  <%=   f.text_field :title %></br>
  </div>
  Tagline:
  <div class="field">
  <%=   f.text_field :tagline %></br>
  </div>
  Body:
  <div class="field">
   <%= f.text_area :body, :class => "tinymce", :rows => 20, :cols => 120, :placeholder => "Tell us about your app." %></br>
  </div><br>
  Link:
  <div class="field">
   <%= f.text_field :link %></br>
  </div>

  <div class="actions">
    <%= f.submit "Submit App" %>
  </div>
<% end %>
 <%= tinymce %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<center><div class="category-title"> <%= link_to 'Post to Apps', new_app_path %></div></center></br>

<tbody>
    <% @apps.reverse.each do |app| %>
      <tr>
       <td>
       <% if (app.created_at) > (24.hours.ago) == true %>
         <div class="time-new"><%= "Today" %> </div>
         <% else %>
         <div class="time">Last updated <%= time_ago_in_words(app.created_at) %> ago </div>
         <% end %>
         </td>
        <td><%= link_to app_path(app) do %> 
        <div class="post-title"><%= app.title %></div></br>
        <% end %> </td>
      </tr>
    <% end %>
  </tbody>
  <%= link_to 'Back', root_url %>
<br>

<div class="category-title">Today's Apps Courtesy of
<%= link_to(image_tag("product-hunt-horizontal-logo-red.png", :width => 200), "http://www.producthunt.com") %></div>

<% client = ProductHunt::Client.new('8564f6856ef80e22f4f70bc7149aa3e4f36089e14a50b8087a50741960a411c1') %>
<% client.posts %>
<% client.posts.each do |attribute| %><br>
<div class="post-title">
<%= attribute['votes_count'] %> votes - <%= link_to "#{attribute['name']}", attribute['redirect_url']%></div>
<%= attribute['tagline'] %><br>
<%= link_to "View in Product Hunt", attribute['discussion_url'] %><br>
<% end %>

  

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>
<div class="title">Apps</div></br>

<div class="category-title"><%= @app.title %></div></br>
Tagline: <%= @app.tagline %></br>
<%= auto_link(simple_format(@app.body)) %></br>
Link: <%= auto_link(simple_format(@app.link)) %><br></br>

<%= link_to 'Back', apps_path %>